### ISSUE TITLE
Published package should not include tests

### ISSUE THREAD

**Issue by mcalthrop** [dominictarr/config-chain#24] opened 2016-03-04 10:03 UTC
The npm package that is published should not include tests.

Background: running into problems in a project I'm working on that uses [flow](http://flowtype.org), which fails (understandably) when trying to process invalid JSON files that are in the `test` directory of this package.

Simple solution is to add a `.npmignore` file containing `test` (per [npm docs: keeping files out of your package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)).

**Comment by dominictarr** [comment] 2016-03-09 10:08
that is a bug in flow, you should post an issue on flow, not here.

**Comment by mcalthrop** [comment] 2016-03-09 15:34
I was following the discussion here: https://github.com/facebook/flow/issues/1420

The gist of it:
* flow is correct in bailing out when it encounters invalid JSON – otherwise it wouldn't be doing its job properly
* it is generally considered a good idea to exclude tests from a published npm package

There are a couple of PRs (#27, #25) that would accomplish this.

What do you reckon?

**Comment by dominictarr** [comment] 2016-03-10 04:46
Yes but it's "checking" code that isn't even in the call graph.
Why is it even looking it the test directory?
This bug should be fixed correctly in flow, merging it here would only encourage flow not to fix it correct.

**Closed by dominictarr** 2016-03-10 04:46 UTC

**Comment by danez** [comment] 2016-03-10 08:14
You are right, that flow should be mor intelligent about which files to parse, but independent of flow it is probably considered a good practice to only include stuff in the npm package that is really needed. And in the case of config-chain this is only the index.js. All the test are not used (hopefully) during runtime.

**Comment by mcalthrop** [comment] 2016-03-10 09:51
I wonder if adding a `main` section to `package.json` would solve the issue?

eg here: https://docs.npmjs.com/getting-started/using-a-package.json#the---yes-init-flag

Perhaps it would indicate to flow (and any other module) where the entry point is.

**Comment by dominictarr** [comment] 2016-03-11 06:05
if `main` is not included, then it defaults to `./index.js`

**Comment by dominictarr** [comment] 2016-03-11 06:47
Also, let me explain why I have my tests included. It wasn't by lazyness, but it's because one day, there will exist a thing that tests all the npm modules, and that thing will be much simpler if the tests are already there, otherwise, it will have to link up to where what commit is that version of the code in github, (that won't be straightforward). I have over 400 modules, and I'm not gonna change my policy about including tests for those modules, except for a really good reason.

**Comment by mcalthrop** [comment] 2016-03-11 15:06
Thanks for taking the time to explain.

What is the new thing that will execute tests in npm modules? (genuine question)

**Comment by dominictarr** [comment] 2016-03-11 20:23
@mcalthrop it doesn't exist yet. I wanted to build it, but currently I'm busy creating technology for [cryptographically secure decentralized social networks](https://github.com/ssbc/scuttlebot/) (front end: https://github.com/ssbc/patchwork )

but I want a thing where, say, you can, before you publish a module, resolve it into  _all_ the modules that might depend on that module, and see if it breaks any their tests, so that you know if you have a breaking change or not. There is other work that would need to happen to enable that, like making npm install _way_ faster.

**Comment by mcalthrop** [comment] 2016-03-14 09:16
Ok. My workaround for the moment is to [exclude node module dirs called `test` from flow config](https://github.com/opencredo/opencredo-react-boilerplate/pull/84/files).

**Comment by bogdansoare** [comment] 2017-11-02 12:22
this is not a bug in flow, please don't publish tests, no major package does that
